# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    restart: unless-stopped
    ports:
      - ${LDAP_PORT:-389}:1389
      - ${LDAPS_PORT:-636}:1636
    env_file: .env
    volumes:
      - './data/ldap:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local
